---
title: "Targeted Metabolomics Workflow"
author: "M. Kohl"
date: "April 2023"
output:
  rmarkdown::html_document:
    toc: true
    number_sections: true
    theme: united
    highlight: tango
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, error = TRUE)
```

# Introduction


# Import of Data

```{r}
load("rawData.RData")
```


```{r}
rawData <- rawData[order(rawData$Gruppe, rawData$'Sample Identification'),]
str(rawData)
```


```{r}
rawData[,1:5]
```


```{r}
concData <- rawData[,seq(from = 8, to = 382, by = 2)]
statusData <- rawData[,seq(from = 9, to = 383, by = 2)]
colnames(statusData) <- colnames(concData)
```


# Quality Control

```{r, fig.width=10}
library(Amelia)
missmap(concData, rank.order = FALSE, y.labels = rawData[,1], 
        x.cex = 0.2)
```


```{r}
NAcols <- colSums(is.na(concData)) > 0
missmap(concData[,NAcols], rank.order = FALSE, y.labels = rawData[,1])
```


```{r}
LOD <- statusData == "< LOD"
Detected <- LOD
LOD[LOD] <- NA
NAcols <- colSums(is.na(LOD)) > 0
missmap(as.data.frame(LOD[,NAcols]), rank.order = FALSE,
        y.labels = rawData[,1], main = "< LOD", legend = FALSE)
LLOQ <- statusData == "< LLOQ"
Detected <- Detected | LLOQ
Detected <- !Detected
LLOQ[LLOQ] <- NA
NAcols <- colSums(is.na(LLOQ)) > 0
missmap(as.data.frame(LLOQ[,NAcols]), rank.order = FALSE,
        y.labels = rawData[,1], main = "< LLOQ", legend = FALSE)
```


```{r}
library(MKomics)
Cor <- cor(t(concData), method = "spearman",
           use = "pairwise.complete.obs")
corPlot(Cor, minCor = 0.95, labels = paste(rawData$Gruppe, rawData[,1]),
        title = "Spearman correlation")
```


# Preprocessing

```{r}
logData <- log2(concData)
logData[logData == -Inf] <- NA
```

```{r}
logFC.dupl <- logData[-11,][seq(1,17,by=2),]-logData[-11,][seq(2,18,by=2),]
boxplot(logFC.dupl, las = 2, main = "log-FC between technical duplicates",
        ylab = "log-FC", cex.axis = 0.6)
abline(h = log2(1.2)*c(-1,1), col = "darkred")
abline(h = log2(1.1)*c(-1,1), col = "darkgreen")
legend("topleft", fill = c("darkgreen", "darkred"),
       legend = c("+/- 10%", "+/- 20%"))
```


```{r}
Qs <- apply(logFC.dupl, 2, quantile, probs = c(0.25, 0.75), na.rm = TRUE)
ausw.var <- Qs[1,] < -log2(1.2) | Qs[2,] > log2(1.2)
boxplot(logFC.dupl[,which(ausw.var)], las = 2, cex.axis = 0.6,
        main = "log-FC between technical duplicates", ylab = "log-FC")
abline(h = log2(1.2)*c(-1,1), col = "darkred")
abline(h = log2(1.1)*c(-1,1), col = "darkgreen")
legend("topleft", fill = c("darkgreen", "darkred"),
       legend = c("+/- 10%", "+/- 20%"))
```


```{r}
normData <- 0.5*logData[-11,][seq(1,17,by=2),]+0.5*logData[-11,][seq(2,18,by=2),]
normData <- rbind(normData[1:5,], logData[11,], normData[6:9,])
normData[apply(normData, 2, is.infinite)] <- NA
ausw.det <- Detected[-11,][seq(1,17,by=2),] | Detected[-11,][seq(2,18,by=2),]
ausw.det <- rbind(ausw.det[1:5,], Detected[11,], ausw.det[6:9,])
```


```{r}
group <- factor(c(rep("Control", 5), rep("Treatment", 5)))
ID <- c(13, 14, 15, 21, 22, 1, 2, 3, 5, 6)
boxplot(t(normData), las = 2, names = group,
        ylab = "log-concentrations", main = "All samples",
        col = "darkgreen")
```


```{r}
library(vsn)
meanSdPlot(t(normData))
```


```{r}
Cor <- cor(t(normData), use = "pairwise.complete.obs")
corPlot(Cor, minCor = 0.95, cex.axis = 0.75, title = "Pearson correlation",
        labels = paste(ID, group, sep = ": "))
```


# Statistical Analysis

```{r}
res <- mod.t.test(t(normData), group = group)
```


```{r}
hist(res$p.value, freq = TRUE, breaks = 100,
     main = "Diagnostic Plot: Distribution of p values",
     xlim = c(0, 1), xlab = "p-values")
```


```{r}
library(MKinfer)
volcano(res$`difference in means`, pval = res$adj.p.value, 
        effect0 = 0, effect.low = -1, effect.high = 1, 
        alpha = 0.25, xlab = "log2-fold Change (log2-FC)",
        ylab = expression(paste(-log[10], "(adj. p Value)")))
```


```{r}
top <- res[which(farbe == "1"),-c(5,7)]
names(top)[1] <- "LogFoldChange"
round(top[order(abs(top[,1]), decreasing = TRUE),], 3)
```


```{r, fig.height=10, fig.width=8}
library(ComplexHeatmap)
library(circlize)
library(RColorBrewer)
## select features
sel <- rownames(top)
selData <- t(normData[,colnames(normData) %in% sel])
## mean centering
selData <- selData - rowMeans(selData, na.rm = TRUE)
selData[is.na(selData)] <- 0
colnames(selData) <- paste(ID, group)
## setting colors
col1 <- rev(brewer.pal(n = 8, name = "RdYlBu"))
col2 <- brewer.pal(n = 3, name = "Set1")[c(3,1)]
mycol <- colorRamp2(seq(-2, 2, length = 128),
                    colorRampPalette(col1)(128))
df <- data.frame(group = group)
ha <- HeatmapAnnotation(df = df,
                        col = list(group = c("Control" = col2[1],
                                             "Treatment" = col2[2])))
set.seed(12345)
Heatmap(selData, col = mycol, name = "log2-FC", show_row_names = TRUE,
        row_names_gp = gpar(fontsize = 7),
        row_names_max_width = unit(2, "cm"),
        top_annotation = ha, show_column_names = TRUE,
        clustering_distance_columns = "pearson",
        show_row_dend = FALSE, km = 4,
        cluster_columns = TRUE, show_column_dend = FALSE,
        column_title = "Metabolites with adj. p < 0.05",
        show_heatmap_legend = TRUE)
```


# Enrichment Analysis

http://www.metaboanalyst.ca/


# Software

```{r}
sessionInfo()
```
