## Benötigte Pakete für die Analyse der Affymetrix Daten
install.packages("BiocManager")
library(BiocManager)
install("affy", update = FALSE)
install("hgu133plus2cdf", update = FALSE)
install("arrayQualityMetrics", update = FALSE)
install.packages("RobLoxBioC")
install("plier", update = FALSE)
install.packages("MKomics")
install.packages("exactRankTests")
install("multtest", update = FALSE)
install.packages("MKinfer")
install("org.Hs.eg.db", update = FALSE)
install("hgu133plus2.db", update = FALSE)
install("GO.db", update = FALSE)
